// Physical fit check: overlays the real PB-3 replacement board (converted
// from the KiCad STEP/GLB export, see kicad/README.adoc and
// .github/workflows/build.yml) inside the measured outer envelope.
// A board that renders fully inside the transparent envelope, with no
// red/solid poking through the walls, confirms the PCB outline matches
// the mechanical envelope proven by the pb3-pack print-fit gauge.
//
// Depends on results/cad/pb3-replacement-board.stl, generated by the CI
// "Render KiCad" step before this file is rendered -- the workflow runs
// KiCad before OpenSCAD for this reason. If the STL is missing (e.g. a
// first local run before the KiCad step), OpenSCAD warns and imports an
// empty shape, so this model still renders the reference envelope alone.
include <include-pb3-envelope.scad>

// Transparent reference envelope.
color("SlateBlue", 0.25) pb3_envelope(emboss_version=false);

// Solid board, imported at the same origin as the envelope.
color("ForestGreen") import("../results/cad/pb3-replacement-board.stl");
